In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("../data/raw/train.csv")

In [3]:
dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
dataset.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [6]:
dataset.shape

(891, 12)

Now let us try to see how many people survived.

In [7]:
dataset.Survived.value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [8]:
dataset.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [9]:
dataset.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [10]:
dataset.Pclass.value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

Now, we should see if survival rates vary by age, class, and sex.

In [11]:
dataset.groupby(["Pclass"])["Survived"].value_counts(normalize=True)

Pclass  Survived
1       1           0.629630
        0           0.370370
2       0           0.527174
        1           0.472826
3       0           0.757637
        1           0.242363
Name: proportion, dtype: float64

These are the survival rates by Pclass (a more concise way to present information in the above cell)
.mean() instead of value_counts(normalize=True) works here because for this dataset, Survived column contains 0s and 1s.

In [12]:
dataset.groupby(["Pclass"])["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [13]:
dataset.groupby(["Sex"])["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Let us create a new column called age_groups with the following age brackets: [0, 16), [16, +inf)

In [14]:
age_bins = [0, 16, 150]
age_labels = ["child", "adult"]

In [15]:
dataset["AgeGroup"] = pd.cut(dataset["Age"], bins=age_bins, labels=age_labels, right=False)

In [16]:
dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,adult

In [17]:
dataset.AgeGroup.value_counts()

AgeGroup
adult    631
child     83
Name: count, dtype: int64

In [18]:
dataset.groupby(["AgeGroup"])["Survived"].mean()

C:\Users\saras\AppData\Local\Temp\ipykernel_25868\691356663.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dataset.groupby(["AgeGroup"])["Survived"].mean()

AgeGroup
child    0.590361
adult    0.381933
Name: Survived, dtype: float64

Now, let us see how the intersection of age, class, and sex impacts survival.

In [19]:
dataset.groupby(["Sex"])["Pclass"].value_counts()

Sex     Pclass
female  3         144
        1          94
        2          76
male    3         347
        1         122
        2         108
Name: count, dtype: int64

In [20]:
dataset.groupby(["Sex", "Pclass"])["Survived"].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

In [21]:
dataset.groupby(["Sex"])["AgeGroup"].value_counts()

Sex     AgeGroup
female  adult       218
        child        43
male    adult       413
        child        40
Name: count, dtype: int64

In [22]:
dataset.groupby(["Sex", "AgeGroup"])["Survived"].mean()

C:\Users\saras\AppData\Local\Temp\ipykernel_25868\1692883093.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dataset.groupby(["Sex", "AgeGroup"])["Survived"].mean()

Sex     AgeGroup
female  child       0.651163
        adult       0.775229
male    child       0.525000
        adult       0.174334
Name: Survived, dtype: float64

In [23]:
dataset.groupby(["Pclass"])["AgeGroup"].value_counts()

Pclass  AgeGroup
1       adult       180
        child         6
2       adult       154
        child        19
3       adult       297
        child        58
Name: count, dtype: int64

In [24]:
dataset.groupby(["Pclass", "AgeGroup"])["Survived"].mean()

C:\Users\saras\AppData\Local\Temp\ipykernel_25868\2779208002.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dataset.groupby(["Pclass", "AgeGroup"])["Survived"].mean()

Pclass  AgeGroup
1       child       0.833333
        adult       0.650000
2       child       1.000000
        adult       0.415584
3       child       0.431034
        adult       0.202020
Name: Survived, dtype: float64

In [25]:
dataset.groupby(["Sex", "Pclass"])["AgeGroup"].value_counts().unstack()

AgeGroup       child  adult
Sex    Pclass
female 1           3     82
       2          10     64
       3          30     72
male   1           3     98
       2           9     90
       3          28    225

In [26]:
dataset.groupby(["Sex", "Pclass", "AgeGroup"])["Survived"].mean()

C:\Users\saras\AppData\Local\Temp\ipykernel_25868\544581589.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dataset.groupby(["Sex", "Pclass", "AgeGroup"])["Survived"].mean()

Sex     Pclass  AgeGroup
female  1       child       0.666667
                adult       0.975610
        2       child       1.000000
                adult       0.906250
        3       child       0.533333
                adult       0.430556
male    1       child       1.000000
                adult       0.377551
        2       child       1.000000
                adult       0.066667
        3       child       0.321429
                adult       0.128889
Name: Survived, dtype: float64